### ISSUE TITLE
links.ff prints an extra "[ dihedrals ]" (but this is not the case for [ bonds ], [ pairs ], and [ angles ])

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#113]
This is mostly a "cosmetic" thing, and doesn't affect the sanity of the itp.

Say you have a link which looks like this:
```
[link]
resname "P3HT|Hter"
[ bonds ]
 CT2  +HTe     2    0.1090  1.2300e+07 {"group": "connect"}
[ pairs ]
 C09  +HTe     1
[ angles ]
 ST1  CT2 +HTe     2     119.0      575.00
[ dihedrals ]
+HTe  ST1  CT3  CT2  2     0.0   167.42309
```

An extra, unnecessary line with the directive `[ XXXXX ] ` will be printed in the generated polymer itp for the `[ dihedrals ]`, so that the polymer itp will look like:

```
[ moleculetype ]
....
[ bonds ]
bonds from the block
bonds from the link
[ pairs ]
pairs from the block
pairs from the link
[ angles ]
angles from the block
angles from the link
[ dihedrals ]
dihedrals from the block
[ dihedrals ]
dihedrals from the link
```
No extra `[ XXXXX ] ` is printed for pairs, bonds, and angles.

**Comment by pckroon** [comment]
Hey hey,

is the separation really blocks vs links, or is it improper vs proper dihedrals? I recall there being something in vermouth regarding this, but I'm fuzzy on the details.

**Comment by fgrunewald** [comment]
@ricalessandri this is due to vermouth printing improper and proper dihedrals in a separate directive. In your case you implemented the P3HT block as itp file, which is fine. But in this case the proper and improper dihedrals are not separated. I'll comment this in your PR. I think it is OK if impropers and porpers are separated.
