### ISSUE TITLE
How to generate copolymer itp files

### ISSUE THREAD

**Issue by nanogchen** [marrink-lab/polyply_1.0#184]
Dear developers,

I was wondering how to create copolymer itp files using polyply, e.g., PVA10-b-PEO10. I went through the homopolymer generation (PVA or PEO) but did not have any clue on how to generate copolymers. I followed PS-b-PEO example in the battery example, but cannot make it for the PVA-b-PEO test. 

The Martini3 force field parameters for each species are known. So the cross-terms between PEO and PVA beads (bond, angles, dihedrals, etc.) are important to me. Any hints given are very much appreciated!

Thanks,
gc

**Comment by fgrunewald** [comment]
Hi gc, 

Excellent question. We have not parametrized all cross terms between the Martini polymers (yet). That's an ongoing effort. PS-b-PEO has been specifically added because of the example in the publication.

In order to make a block copolymer you have to define the linking interactions (i.e. bonds and angles, and if you want dihedrals). To do that you can run a small co-polymer of PVA-b-PEO in water at the all atom level and then map it to Martini and extract the parameters. The steps involved are essentially the same as in this [tutorial](http://cgmartini.nl/index.php/2021-martini-online-workshop/tutorials/560-5-parametrization-of-a-new-small-molecule) but instead of targeting a small molecule you only parametrize the missing link between the blocks. 

Note you can generate the atomistic simulation with polyply as well using the 2016H66 force-field. Something like the following should produce a usable itp and then you solvate it in water and run for like 20-50ns.

```
polyply gen_params -lib 2016H66 -seq PEO:5 PVA:5 -o PVA_PEO_AA.itp -name test
```

Once you've done that you simply write an ff-file as follows:

```
[link]
resname "PEO|PVA"
[ bonds ]
VNL >EC 1 <length> <force-constant>
[ angles ]
<VNL VNL >EC 2  <angel> <force-constant>
VNL >EC >>EC 2  <angel> <force-constant>
```
If you don't want to do it yourself you'll have to wait for us to derive those interactions. I could probably do it next week, but I'm not giving guarantees. In case you want to wait let me know in a reply than I can prioritize PVA-b-PEO.

Hope this helps!
Fabian

**Comment by nanogchen** [comment]
Hi Fabian,

Thank you very much for your prompt response and the help you offered. I am happy to wait for it as I'm just entering Martini CG simulation recently. I'll be happy to learn the tutorial you shared. If there is anything I can do, please let me know.

Thanks again,
gc

**Comment by fgrunewald** [comment]
Hi, 

Alright no worries. I'll leave this issue open until I've uploaded the PVA-b-PEO parameters. Then you will get an notification. If you're new to CG Martini in general I highly recommend the Tutorial I sent and the others linked in the same place.

Cheers,
Fabian

**Comment by nanogchen** [comment]
Awesome, I'll check it out. Thanks.

Best,
gc
