### ISSUE TITLE
molecule consists of 3 disjoint parts

### ISSUE THREAD

**Issue by AGGA32** [marrink-lab/polyply_1.0#186]
Hello,

I am trying to create an Ethylene glycol CG molecule. Below are my inputs for EG generation:
`polyply gen_params -lib martini3 -o DEG_MARTINI.itp -name DEG -seq OHter:1 PEO:1 OHter:1`

After finishing the generation, I got this warning:
`WARNING - general - You molecule consists of 3 disjoint parts. Perhaps links were not applied correctly.`

Is there anything wrong with my input arguments?

**Comment by ricalessandri** [comment]
Hi,

I tried to run that command and nothing's wrong with your input arguments as far as I can tell. In fact, I think this is something that should get fixed on the code end. As I understand you're trying to make a model for di-ethyeleneglycol which should indeed be a TP1-SN3r-TP1 model. However, polyply is not adding the bonds, hence the warning.

Let me bring this to the attention of @fgrunewald - what do you think? Maybe the bonds don't get printed in the final output because the [ link ] block expects to find at least 2 EC (aka SN3r) beads?
I tried:
```
polyply gen_params -lib martini3 -o DEG_MARTINI.itp -name DEG -seq OHter:1 PEO:2 OHter:1
polyply gen_params -lib martini3 -o DEG_MARTINI.itp -name DEG -seq OHter:1 PEO:3 OHter:1
```
and they both work as expected.

**Comment by fgrunewald** [comment]
Hey guys,

This is a bit of a security feature. We currently don't have the angle
potential associated with OH-PEO-OH so it doesn't add the link. There are
two options to resolve this: 1) you derive the angle or 2) ignore the angle
and just use the bonds.

I'm currently working from abroad, so I don't have time to add the
parameters until I'm back in March. Perhaps Riccardo can help from here.

Cheers,
Fabian


Riccardo Alessandri ***@***.***> schrieb am So., 6. Feb.
2022, 09:22:

**Comment by ricalessandri** [comment]
That makes sense. 

@AGGA32 let me know if you need some more details on option 1) if you decide to go for that ([this tutorial](http://www.cgmartini.nl/index.php/2021-martini-online-workshop/tutorials/560-5-parametrization-of-a-new-small-molecule) describes the way to do it).

**Comment by AGGA32** [comment]
Thank you @ricalessandri for offering your assistance. I have one question regarding option 1.  The CG beads that I will be using will come from [Grunewald et al. - 2018 - Transferable MARTINI Model of Poly(ethylene Oxide).pdf](https://github.com/marrink-lab/polyply_1.0/files/8013321/Grunewald.et.al.-.2018.-.Transferable.MARTINI.Model.of.Poly.ethylene.Oxide.pdf). I would like to clarify if this study used MARTINI v2.0 instead of MARTINI 3.0? Also, should I include the hydrogen atoms when generating CG beads on **CGBuilder** based on the tutorial you provided?

Take care,

Alexis

**Comment by ricalessandri** [comment]
That paper uses mostly Martini 2, but then also introduced a preliminary model for PEO with Martini 3 in the Supporting Information, section 6.

So, if you want to use Martini 3, you should refer to the new bead types that polyply produces (i.e, **TP1** bead for the OH termini of PEG and the **SN3r** for the PEO repeat unit) because that's the current best model. If you want to go for the Martini 2 version, you should indeed use the beads in that paper. You can access those parameters with popyply by using a similar command to the ones above but then calling the `martini2` library instead of the `martini3` one.

Regarding your CGBuilder question: yes, you should indeed include the hydrogen atoms when mapping the structure to CG beads since we now use center-of-geometry (COG) mapping *including the hydrogens* in Martini 3 when deriving bonded parameters.

**Comment by AGGA32** [comment]
Thank you @ricalessandri. I will ask you again if I have trouble implementing option 1.

**Comment by AGGA32** [comment]
Hello,

I already followed the tutorial up to the 6th part. I already generated the bonds and angles of each bead and I already updated my '.itp' file based on the bonds and angles distribution. May I ask if there is a way to generate the coordinate file? I have the '3-run.gro' but I don't know if the coordinates of the polymer are already based on the data generated by '6_generate_CG_distr'?

**Comment by AGGA32** [comment]
I understand your statement @ricalessandri. I will also use `gmx cluster` to get a representative structure. Thank you again.

**Comment by ricalessandri** [comment]
Bonded parameters such as angles and bonds will not be affected but a change in temperature, especially when so small. So, you can either go for 310.15 K or stick to 298.15 K and it won't affect the bond/angle distributions. 
(You could also give it a shot and verify that if you're curious ;))
