### ISSUE TITLE
Tutorial: PEGylated proteins - molecule consists of 4 disjoint parts

### ISSUE THREAD

**Issue by smilerrrr** [marrink-lab/polyply_1.0#212]
Hi Developer,

I did some procedures just like the PEGlyted-Protein Tutorial but it gives me "**WARNING - general - You molecule consists of 4 disjoint parts. Perhaps links were not applied correctly**". I don't understand how to solve this problem. My command is just the same as the tutorial and the issue #205 . 
```
polyply gen_seq -f molecule_0.itp -from_file protein:molecule_0\
                           -from_string linker:1:1:MEE-1.0 polymer:50:1:PEO-1.0 end:1:1:OHend-1.0\
                           -seq protein linker polymer end\
                           -connects 0:1:0-0 1:2:0-0 2:3:49-0\
                           -o sequence.json -name test\
                           -label 0:"from_itp":"molecule_0-1."
```
```
polyply gen_itp -f molecule_0.itp MEE.itp methoxy_link.ff PEO.martini.3b.itp OH_end.itp -seqf sequence.json -o lysoPEG.itp -name lysoPEG
```

Could you help me with that?

**Comment by fgrunewald** [comment]
@smilerrrr Yes indeed. Sorry about that. You need the `combined_links.ff` file instead of the `methoxy_link.ff`. But even when I run your command on the current setup I get 2 disjoint parts not 4. So perhaps something else is going on. Can you try with the combined links and also update your polyply version to 1.3.

**Comment by fgrunewald** [comment]
@smilerrrr did it work out for you?
