### ISSUE TITLE
Provide some mdp files for energy minimization (and equilibration)? 

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#90]
I was thinking, since some systems - well, at least, P3HT - need a relatively less-common minimization procedure once generated, i.e., 100 steps of energy minimization with soft-core potentials, maybe it can be good to provide such mdps to the user? Not everybody might be familiar with it. Otherwise, just throw a little warning when expected that soft-core minimization would be necessary.

**Comment by fgrunewald** [comment]
This is very true and linked to PR #64, where polyply would actually call gromacs to do an iterative energy minimization. This PR didn't get merged because @pckroon  and I were thinking about a general way of writing gromacs pipelines, but I think I will revisit this PR soon. Or perhaps you are interested in doing so?

**Comment by fgrunewald** [comment]
We will be adding tutorial files, which contain both mdp files and parameter files. This will at least make them available from the tutorial setting. Other than that I think we can only provide files for energy minization otherwise we'd have to parse and keep track to too many parameters involving temperature, pressure, time-steps, etc.
